import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full flex flex-col`}
      >
        <main className="flex-1 flex flex-col">{children}</main>
        <footer className="absolute bottom-0 right-0 p-2 text-md">
          Individual Project by Napasorn Tevarut 6510545519
        </footer>
      </body>
    </html>
  );
}
